### ISSUE TITLE
特定情况下 时间节点切换前后小组件会出现显示错误

### ISSUE THREAD

**Issue by Yersmagit** [Class-Widgets/Class-Widgets#109]
### 检查清单

- [x] 我已更新到最新版 ![GitHub Release](https://img.shields.io/github/v/release/RinLit-233-shiroko/Class-Widgets?include_prereleases) ，并看过[最新提交](https://github.com/RinLit-233-shiroko/Class-Widgets/commits/main/)，确认这一 Bug 还没有修复。
- [X] 我已在 [Issues](https://github.com/RinLit-233-shiroko/Class-Widgets/issues?q=label%3ABug) 中检索，确认这一 Bug 未被提交过。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题（关于其他非程序本身的问题应当在 Discussion 板块提出）。

### 期望的行为

如果设定的 上一节点的最后一个课程的结束时间 与 下一节点开始时间 的间隔小于 30min **（大约数）**，程序应当 **在上一节点最后一个课程结束时** 更新下一节点的课程信息，而不是在上一个时间节点的课程还在进行时就更新课程信息。更新课程信息时不应覆盖原有的当前活动信息和活动倒计时文本。

### 实际结果

如果设定的 上一节点的最后一个课程的结束时间 与 下一节点开始时间 的间隔小于 30min **（大约数）**，程序就会在上一个节点最后一个课程还在进行时就更新下一个节点的课程信息。更新课程信息后，当前活动会显示为“暂无课程”，活动倒计时文本则显示为“距离上课还有 --:--”_（如下图所示）_
![截图01](https://github.com/user-attachments/assets/56989f4e-232c-4fad-83de-b764d6a92399)

### 重现步骤

1. 设定时间线。时间线应包含两个节点， 上一个节点的最后一个课程的**结束时间** 与 下一节点**开始时间** 的间隔应小于 30min **（大约数）**。

   _（如例图所示，上午最后一个课程的结束时间为 16:22 + 33min = 16:55 ，与下午开始时间的间隔为 0min ，小于 30min ）_
   ![截图02](https://github.com/user-attachments/assets/76667060-eb82-4e19-8b44-6f0885acb4a1)

   _（为方便理解，在此也展示了设定的课程）_
   ![截图03](https://github.com/user-attachments/assets/8ada1e55-d11c-47b0-9f8b-b352b62c9c66)

3. 等待上一个节点的最后一个课程开始。
4. 在距离下一个节点开始还剩 30min **（大约数）** 时（此时上一节点的最后一个课程还在进行），下一个节点的课程信息更新，此时当前活动与活动倒计时文本显示出现错误。

   _〔如例图所示，当前活动显示为“暂无课程”（此时这节课设定的是数学），活动倒计时文本则显示为“距离上课还有 --:--”〕_
   ![截图01](https://github.com/user-attachments/assets/56989f4e-232c-4fad-83de-b764d6a92399)

### 应用版本

1.1.7-b2

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题。如果我的 issue 没有按照上述的要求填写，可能会被无条件关闭。

### 不要乱下载别人发的文件，特别是名字是fix.zip的文件。您是否遇见过这样的文件？

否

**Comment by got991** [comment]
成功复现。
并且在这种情况下的主题色并非课间主题色，而是上课时的主题色。

**Comment by got991** [comment]
重启后似乎有可能恢复正常（上周在学校测的）

**Comment by RinLit-233-shiroko** [comment]
已在 abad94c 中更改获取节点的逻辑，已修复。
