### ISSUE TITLE
小浮窗似乎存在Bug

### ISSUE THREAD

**Issue by SparkleUesegi** [Class-Widgets/Class-Widgets#111]
### 检查清单

- [X] 我已更新到最新版 ![GitHub Release](https://img.shields.io/github/v/release/RinLit-233-shiroko/Class-Widgets?include_prereleases) ，并看过[最新提交](https://github.com/RinLit-233-shiroko/Class-Widgets/commits/main/)，确认这一 Bug 还没有修复。
- [X] 我已在 [Issues](https://github.com/RinLit-233-shiroko/Class-Widgets/issues?q=label%3ABug) 中检索，确认这一 Bug 未被提交过。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题（关于其他非程序本身的问题应当在 Discussion 板块提出）。

### 期望的行为

小浮窗正常弹出并回到上次调整的位置

### 实际结果

小浮窗**文字、环状图显示不完全**
![屏幕截图 2024-10-21 172606](https://github.com/user-attachments/assets/6e0e8b6b-6fde-439d-99de-6289f80a33d8)
有时甚至会出现在**原主窗口的位置并向上方隐藏**

### 重现步骤

1.自动隐藏选择 无 
2.选择 最小化为浮窗 
3.移动小浮窗位置
4.恢复成原窗口
5.自动隐藏选择 上课时自动隐藏 
6.等待上课时间

### 应用版本

1.1.7_b3

### 操作系统版本

11.0.22631.4317

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题。如果我的 issue 没有按照上述的要求填写，可能会被无条件关闭。

### 不要乱下载别人发的文件，特别是名字是fix.zip的文件。您是否遇见过这样的文件？

否

**Comment by RinLit-233-shiroko** [comment]
目前暂未复现，能提供更多信息吗

**Comment by SparkleUesegi** [comment]
> 目前暂未复现，能提供更多信息吗

在重新安装后又解决了（？）

**Comment by SparkleUesegi** [comment]
![屏幕截图 2024-10-22 103031](https://github.com/user-attachments/assets/ba39325f-3df6-4446-ba5b-05046ea6889b)
又出现了，不过可以拖下来后点击使其恢复正常

**Comment by SparkleUesegi** [comment]
似乎快速点击小浮窗和主窗口进行切换时也会引发此Bug

https://github.com/user-attachments/assets/8891f773-505c-434c-b2ac-66fd2954f688

**Comment by RinLit-233-shiroko** [comment]
打断动画的问题已经修复了

**Comment by SparkleUesegi** [comment]
> 打断动画的问题已经修复了

3q😊
