### ISSUE TITLE
删除某个时段导致设置不可用

### ISSUE THREAD

**Issue by WRMYX** [Class-Widgets/Class-Widgets#123]
### 检查清单

- [X] 我已更新到最新版 ![GitHub Release](https://img.shields.io/github/v/release/RinLit-233-shiroko/Class-Widgets?include_prereleases) ，并看过[最新提交](https://github.com/RinLit-233-shiroko/Class-Widgets/commits/main/)，确认这一 Bug 还没有修复。
- [X] 我已在 [Issues](https://github.com/RinLit-233-shiroko/Class-Widgets/issues?q=label%3ABug) 中检索，确认这一 Bug 未被提交过。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题（关于其他非程序本身的问题应当在 Discussion 板块提出）。

### 期望的行为

删除某个时段导致设置可用

### 实际结果

删除某个时段导致设置不可用
https://github.com/user-attachments/assets/bbfd20bc-f4ba-4af3-967a-35276844c658

### 重现步骤

1.删除就餐这个时间段
2.课程表下载（https://www.123pan.com/s/iUrajv-ioH8v）

### 应用版本

1.1.7-b3

### 操作系统版本

23H2

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题。如果我的 issue 没有按照上述的要求填写，可能会被无条件关闭。

### 不要乱下载别人发的文件，特别是名字是fix.zip的文件。您是否遇见过这样的文件？

否

**Comment by RinLit-233-shiroko** [comment]
收到，下个版本会修复此Bug。
若您需要解决此问题，请直接打开您的课表文件，然后对timeline部分把删除的时段的课程、课间删除即可。

> **e.g.**
> 假设这是您的课程表文件（部分）：

```
{
    "part_name":{
        "0":[
            xx,
            xx
        ]
        "1":[  //假设您删去了第二个时段（"1"为时段的排列顺序）
            xx,
            xx
        ],
        "2":[
            xx,
            xx
        ]
    },
"timeline": {
        "default": {
            "a01": "45",
            "f01": "15",
            "a02": "20",

            //要删去的部分↓（即"ax1/fx1"中第二个字符为您所删的时段的顺序）
            “a11": "40",
            "f11": "10",
            "a12": "40",

            “a21": "40",
            "f21": "10",
            "a22": "40"
        },
        "0": {},
        "1": {},
        "2": {},
        "3": {},
        "4": {},
        "5": {},
        "6": {}
    }
}
```

**Comment by RinLit-233-shiroko** [comment]
现在已在最新版本修复
