### ISSUE TITLE
每个节点最后一节课下课时的上下课提醒缺失

### ISSUE THREAD

**Issue by Yersmagit** [Class-Widgets/Class-Widgets#126]
### 检查清单

- [X] 我已更新到最新版 ![GitHub Release](https://img.shields.io/github/v/release/RinLit-233-shiroko/Class-Widgets?include_prereleases) ，并看过[最新提交](https://github.com/RinLit-233-shiroko/Class-Widgets/commits/main/)，确认这一 Bug 还没有修复。
- [X] 我已在 [Issues](https://github.com/RinLit-233-shiroko/Class-Widgets/issues?q=label%3ABug) 中检索，确认这一 Bug 未被提交过。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题（关于其他非程序本身的问题应当在 Discussion 板块提出）。

### 期望的行为

到达每个节点最后一节课下课时，可以正常进行上下课提醒

### 实际结果

到达每个节点最后一节课下课时，上下课提醒缺失（上下课提醒开关已打开）。
此问题似乎是修复 #107 导致的。

### 重现步骤

1. 设置时间线
2. 等待到达节点的最后一节课下课
3. 问题出现

### 应用版本

1.1.7-b3

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题。如果我的 issue 没有按照上述的要求填写，可能会被无条件关闭。

### 不要乱下载别人发的文件，特别是名字是fix.zip的文件。您是否遇见过这样的文件？

否

**Comment by RinLit-233-shiroko** [comment]
emm没能复现出来，能提供更多数据吗

**Comment by MKStoler4096** [comment]
有的

**Comment by RinLit-233-shiroko** [comment]
等一下，终于复现出来了，尝试修复

**Comment by RinLit-233-shiroko** [comment]
能给出课程表文件吗

**Comment by wuyufeng9960** [comment]
我这里有一份也能有类似bug的课表
[config.zip](https://github.com/user-attachments/files/17543656/config.zip)

**Comment by MKStoler4096** [comment]
其实只要最后一节课后有课间就没问题

**Comment by RinLit-233-shiroko** [comment]
> 其实只要最后一节课后有课间就没问题

再次测试了一下，发现在Beta3确实有此Bug且能稳定触发，但是在最新的库中却莫名被修复了。

**Comment by wuyufeng9960** [comment]
> 其实只要最后一节课后有课间就没问题

我这边这个方法好像也不行，只会误导同学们不知道下晚自习了（学校没有铃声）

**Comment by wuyufeng9960** [comment]
我认为这个问题可能是在添加单独的上下课铃声开关时出现的
被修复的原因也许是在打包时没有初始化铃声开关？

**Comment by RinLit-233-shiroko** [comment]
> 我认为这个问题可能是在添加单独的上下课铃声开关时出现的 被修复的原因也许是在打包时没有初始化铃声开关？

这个就不清楚了w(ﾟДﾟ)w
