### ISSUE TITLE
自定义界面不能自适应缩放

### ISSUE THREAD

**Issue by happytbs** [Class-Widgets/Class-Widgets#130]
### 检查清单

- [X] 我已更新到最新版 ![GitHub Release](https://img.shields.io/github/v/release/RinLit-233-shiroko/Class-Widgets?include_prereleases) ，并看过[最新提交](https://github.com/RinLit-233-shiroko/Class-Widgets/commits/main/)，确认这一 Bug 还没有修复。
- [X] 我已在 [Issues](https://github.com/RinLit-233-shiroko/Class-Widgets/issues?q=label%3ABug) 中检索，确认这一 Bug 未被提交过。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题（关于其他非程序本身的问题应当在 Discussion 板块提出）。

### 期望的行为

![image](https://github.com/user-attachments/assets/45b9ab87-5285-426a-b55c-55718088d996)
应该是可以随着屏幕缩放自适应的

### 实际结果

![image](https://github.com/user-attachments/assets/894a2646-0932-4558-82de-79c77f49cde9)
这是自定义页面，可以看到下面有滚动条，只能有一个固定大小，窗口缩小后会导致内容缺失

### 重现步骤

1.从托盘打开设置
2.点击左侧栏的自定义界面
3.将窗口缩小

### 应用版本

1.1.7-b3

### 操作系统版本

22635.4435

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题。如果我的 issue 没有按照上述的要求填写，可能会被无条件关闭。

### 不要乱下载别人发的文件，特别是名字是fix.zip的文件。您是否遇见过这样的文件？

否

**Comment by RinLit-233-shiroko** [comment]
抱歉，忘记给下面的caption开换行了，会在下个版本修复
