### ISSUE TITLE
软件运行时无法清空日志（？？？）

### ISSUE THREAD

**Issue by happytbs** [Class-Widgets/Class-Widgets#131]
### 检查清单

- [X] 我已更新到最新版 ![GitHub Release](https://img.shields.io/github/v/release/RinLit-233-shiroko/Class-Widgets?include_prereleases) ，并看过[最新提交](https://github.com/RinLit-233-shiroko/Class-Widgets/commits/main/)，确认这一 Bug 还没有修复。
- [X] 我已在 [Issues](https://github.com/RinLit-233-shiroko/Class-Widgets/issues?q=label%3ABug) 中检索，确认这一 Bug 未被提交过。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题（关于其他非程序本身的问题应当在 Discussion 板块提出）。

### 期望的行为

点击清空日志弹出消息提醒清空成功

### 实际结果

![image](https://github.com/user-attachments/assets/7c82b79d-23e2-4789-9ca0-d4692ade9f89)
显示如上文字（程序占用的日志导致无法清空？）

### 重现步骤

1.打开设置
2.选择高级选项
3.拉到最底下点击清空日志

### 应用版本

1.1.7-b3

### 操作系统版本

22635.4435

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题。如果我的 issue 没有按照上述的要求填写，可能会被无条件关闭。

### 不要乱下载别人发的文件，特别是名字是fix.zip的文件。您是否遇见过这样的文件？

否

**Comment by MKStoler4096** [comment]
这个日志是程序在使用的（）

**Comment by RinLit-233-shiroko** [comment]
ok收到，待会改改

**Comment by MKStoler4096** [comment]
已经完成了，可以关了。
