### ISSUE TITLE
插件功能

### ISSUE THREAD

**Issue by leohu1** [Class-Widgets/Class-Widgets#145]
### 检查清单

- [X] 我已更新到最新版 ![最新的版本号](https://img.shields.io/github/v/release/RinLit-233-shiroko/Class-Widgets?include_releases&style=flat-square&label=) ，并看过[最新提交](https://github.com/RinLit-233-shiroko/Class-Widgets/commits/main/)，确认我想要的功能还没有实现。
- [X] 我已在 [Issues](https://github.com/RinLit-233-shiroko/Class-Widgets/issues?q=label%3ABug) 中检索，确认这一 Bug 未被提交过。
- [X] 我认为我想要的功能是用户广泛需要的，插件不能替代的，且没有超出 **软件本来** 的开发目标，而非 **添加与课表及教学辅助无关的内容** 。
- [X] 我已知晓由于开发者时间精力有限，我提交的功能请求可能需要比较久的时间才能实现。

### 背景与动机

老师上课可能会用特定软件，希望可以预先启动以提高课堂效率
这个功能过于自定义化，希望提供插件功能以实现此类高度自定义化功能

### 想要实现或优化的功能

读取调用```.py```插件，
提供上课，下课，预备铃等接口（自动执行），
同时希望提供调用通知栏的接口

### 最后一步

- [X] 我认为上述的描述已经足以详细，以便开发人员理解您想要的功能。如果我的 issue 没有按照上述的要求填写，可能会被无条件关闭。

**Comment by Detritalw** [comment]
这个没必要吧...
真的想要可以试试电脑自带的任务计划程序（**taskschd.msc**）。
快捷启动希沃就做了，没准装个希沃桌面就有...

**Comment by RinLit-233-shiroko** [comment]
会考虑的

**Comment by RinLit-233-shiroko** [comment]
已在 [83589e5](https://github.com/RinLit-233-shiroko/Class-Widgets/commit/83589e52c8b792bead4650f748c2bf17f0750e19) 尝试实现
