### ISSUE TITLE
小伙以为发现了bug，没想到这竟是开发者大大故意的！此举一出，大获关注。更多资讯请访问Class-Widgets新闻

### ISSUE THREAD

**Issue by herobrinein** [Class-Widgets/Class-Widgets#147]
### 检查清单

- [X] 我已更新到最新版 ![GitHub Release](https://img.shields.io/github/v/release/RinLit-233-shiroko/Class-Widgets?include_prereleases) ，并看过[最新提交](https://github.com/RinLit-233-shiroko/Class-Widgets/commits/main/)，确认这一 Bug 还没有修复。
- [X] 我已在 [Issues](https://github.com/RinLit-233-shiroko/Class-Widgets/issues?q=label%3ABug) 中检索，确认这一 Bug 未被提交过。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题（关于其他非程序本身的问题应当在 Discussion 板块提出）。

### 期望的行为

点击任务栏图标隐藏课表，按照设置中设好的方式的隐藏

### 实际结果

https://github.com/user-attachments/assets/8c2c1d47-e9c4-4532-838d-6361512d5463

### 重现步骤

1.在设置中将"隐藏方式"改为浮窗
2.在任务栏点击图标来隐藏课表

### 应用版本

1.1.7-b3

### 操作系统版本

Windows 11 24H2 (OS内部版本 26100.1742)

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题。如果我的 issue 没有按照上述的要求填写，可能会被无条件关闭。

**Comment by baiyao105** [comment]
看起来不应该是bug标签🤔

**Comment by RinLit-233-shiroko** [comment]
这不是bug捏，不过如果不满意的话会改的

**Comment by herobrinein** [comment]
啊？这是故意的？

**Comment by RinLit-233-shiroko** [comment]
（）
