### ISSUE TITLE
重复设置调课后课程表文件损坏

### ISSUE THREAD

**Issue by Yersmagit** [Class-Widgets/Class-Widgets#150]
### 检查清单

- [X] 我已更新到最新版 ![GitHub Release](https://img.shields.io/github/v/release/RinLit-233-shiroko/Class-Widgets?include_prereleases) ，并看过[最新提交](https://github.com/RinLit-233-shiroko/Class-Widgets/commits/main/)，确认这一 Bug 还没有修复。
- [X] 我已在 [Issues](https://github.com/RinLit-233-shiroko/Class-Widgets/issues?q=label%3ABug) 中检索，确认这一 Bug 未被提交过。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题（关于其他非程序本身的问题应当在 Discussion 板块提出）。

### 期望的行为

设置调课后仍可正常再次设置调课

### 实际结果

重复设置调课后，重启软件，课程表文件损坏，无法恢复原状

### 重现步骤

1. 打开软件，设置调课并保存

   * 此时程序生成 `backup.json` 课表备份，原课表文件 `example.json`[^1] 更改，一切正常
[^1]: 此处课表文件名称以 `example.json` 举例

2. 关闭调课界面窗口后重新打开窗口

3. 再次设置调课并保存
   * 此时程序用第 1 步设置调课后的课表文件 `example.json` 覆盖了 `backup.json` 课表备份，问题至此出现

4. 重启应用，原课表文件 `example.json` 无法恢复原状，仍然使用第 1 步设置的调课课表

### 应用版本

1.1.7-b3

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题。如果我的 issue 没有按照上述的要求填写，可能会被无条件关闭。

**Comment by RinLit-233-shiroko** [comment]
收到，会修复的
