### ISSUE TITLE
Win11 下 设置和额外选项的窗口控件图标显示异常

### ISSUE THREAD

**Issue by Yersmagit** [Class-Widgets/Class-Widgets#151]
### 检查清单

- [X] 我已更新到最新版 ![GitHub Release](https://img.shields.io/github/v/release/RinLit-233-shiroko/Class-Widgets?include_prereleases) ，并看过[最新提交](https://github.com/RinLit-233-shiroko/Class-Widgets/commits/main/)，确认这一 Bug 还没有修复。
- [X] 我已在 [Issues](https://github.com/RinLit-233-shiroko/Class-Widgets/issues?q=label%3ABug) 中检索，确认这一 Bug 未被提交过。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题（关于其他非程序本身的问题应当在 Discussion 板块提出）。

### 期望的行为

在 Win11 下，设置和额外选项的窗口控件图标能如 1.1.7-b2 及以前的版本一样，正常使用 Win11 内置的样式

### 实际结果

设置和额外选项的窗口控件图标使用了 Win10 的样式（如图

![image](https://github.com/user-attachments/assets/b49f3eb4-dd74-4219-9c31-6c643dde0c8f)
*_上图的上方是 ClassWidgets 设置页面的窗口控件，下方是系统设置的窗口控件_

### 重现步骤

1. 打开设置或额外选项
2. 问题出现

### 应用版本

1.1.7-b3

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题。如果我的 issue 没有按照上述的要求填写，可能会被无条件关闭。

**Comment by RinLit-233-shiroko** [comment]
这个算是组件库的问题吧，并且影响不大，短期内不会考虑修复
