### ISSUE TITLE
作者大大能否加速打包beta4

### ISSUE THREAD

**Issue by wuyufeng9960** [Class-Widgets/Class-Widgets#155]
### 检查清单

- [X] 我已更新到最新版 ![最新的版本号](https://img.shields.io/github/v/release/RinLit-233-shiroko/Class-Widgets?include_releases&style=flat-square&label=) ，并看过[最新提交](https://github.com/RinLit-233-shiroko/Class-Widgets/commits/main/)，确认我想要的功能还没有实现。
- [X] 我已在 [Issues](https://github.com/RinLit-233-shiroko/Class-Widgets/issues?q=label%3ABug) 中检索，确认这一 Bug 未被提交过。
- [X] 我认为我想要的功能是用户广泛需要的，插件不能替代的，且没有超出 **软件本来** 的开发目标，而非 **添加与课表及教学辅助无关的内容** 。
- [X] 我已知晓由于开发者时间精力有限，我提交的功能请求可能需要比较久的时间才能实现。

### 背景与动机

在使用b3的过程中我遇到了许多问题，并且这些问题似乎均已被修复，希望作者可以固定一个时间进行新版本的打包，谢谢

### 想要实现或优化的功能

希望作者可以定期进行新的beta版发布，谢谢！！！

### 最后一步

- [X] 我认为上述的描述已经足以详细，以便开发人员理解您想要的功能。如果我的 issue 没有按照上述的要求填写，可能会被无条件关闭。

**Comment by xuanxuan1231** [comment]
可以自行在action下载最新构建

**Comment by wuyufeng9960** [comment]
我电脑上库比较杂，动不动就报错…………

**Comment by xuanxuan1231** [comment]
我指的是在Action的build中下载工件，每次提交都会自动构建一次。如果需要在电脑上以源代码运行，建议使用虚拟环境。

**Comment by SL-Studio-ST** [comment]
期待

**Comment by wuyufeng9960** [comment]
用了2年的github才知道，长知识了（但希望作者大大还是能够快些打包）
