### ISSUE TITLE
程序上课时自动隐藏为浮窗时挤在屏幕顶端

### ISSUE THREAD

**Issue by alexliu07** [Class-Widgets/Class-Widgets#156]
### 检查清单

- [X] 我已更新到最新版 ![GitHub Release](https://img.shields.io/github/v/release/RinLit-233-shiroko/Class-Widgets?include_prereleases) ，并看过[最新提交](https://github.com/RinLit-233-shiroko/Class-Widgets/commits/main/)，确认这一 Bug 还没有修复。
- [X] 我已在 [Issues](https://github.com/RinLit-233-shiroko/Class-Widgets/issues?q=label%3ABug) 中检索，确认这一 Bug 未被提交过。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题（关于其他非程序本身的问题应当在 Discussion 板块提出）。

### 期望的行为

设置了上课时自动隐藏后，程序在上课时会自动隐藏为浮窗

### 实际结果

在上课提醒显示完毕后，浮窗会挤在屏幕顶端，有时候会直接消失

https://github.com/user-attachments/assets/f795e95f-6d24-430d-9784-d521c5b3d973

在此时，如果将隐藏方式切换为默认，则隐藏条会和浮窗同时显示在屏幕上

https://github.com/user-attachments/assets/9eeb24c9-ff6e-4aea-88e4-5aef0cb229e4

此问题为概率复现，但是在学校和家里的电脑上均可以复现

### 重现步骤

1. 将 **隐藏方式** 设置为 _最小化为浮窗_
2. 将 **自动隐藏** 设置为 _上课时自动隐藏_
3. 等待上课提醒
4. 有概率出现这个问题

### 应用版本

1.1.7-b4 commit ec31219

### 操作系统版本

10.0.22631.4541

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题。如果我的 issue 没有按照上述的要求填写，可能会被无条件关闭。

**Comment by RinLit-233-shiroko** [comment]
az不好复现啊

**Comment by alexliu07** [comment]
测试了一下
浮窗压缩：在main.py的710行设置浮窗尺寸中，调用了self.setMinimumSize，程序将长和宽都除以了self.zoom，而self.zoom的值被设置为2，所以导致浮窗被压缩，将708行定义的self.zoom的初始值改为1可以解决这个问题，但我不太清楚self.zoom这个变量的作用
窗口位置在屏幕顶端：在main.py的第721~723行中，调用了self.animation_rect.setStartValue，在传入的值中的第二个参数默认值为-50，通过调试可以发现浮窗此时的位置高度正是-50，将这个参数改为0就可以让浮窗显示在屏幕上了，不过我也不太清楚animation_rect的作用
![image](https://github.com/user-attachments/assets/8de26d85-df98-4ca8-90a4-521684122661)

**Comment by RinLit-233-shiroko** [comment]
> 测试了一下 浮窗压缩：在main.py的710行设置浮窗尺寸中，调用了self.setMinimumSize，程序将长和宽都除以了self.zoom，而self.zoom的值被设置为2，所以导致浮窗被压缩，将708行定义的self.zoom的初始值改为1可以解决这个问题，但我不太清楚self.zoom这个变量的作用 窗口位置在屏幕顶端：在main.py的第721~723行中，调用了self.animation_rect.setStartValue，在传入的值中的第二个参数默认值为-50，通过调试可以发现浮窗此时的位置高度正是-50，将这个参数改为0就可以让浮窗显示在屏幕上了，不过我也不太清楚animation_rect的作用 ![image](https://private-user-images.githubusercontent.com/101923999/390834228-8de26d85-df98-4ca8-90a4-521684122661.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI4NTk5ODEsIm5iZiI6MTczMjg1OTY4MSwicGF0aCI6Ii8xMDE5MjM5OTkvMzkwODM0MjI4LThkZTI2ZDg1LWRmOTgtNGNhOC05MGE0LTUyMTY4NDEyMjY2MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyOVQwNTU0NDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lZTFkNGI0ZGMwNTFiZWI2MmZmNzhmY2VjNDc1NDJjNDAwYjUwZDkxN2Y5MTY2MjY1Y2RhMjg4Y2U3ZjAzMTgyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.pP0dmwjXy9KfC9tK0kClRumJRIEDrs3iZV8KruQMs_I)

实际上这是动画效果，如视频内容所示：

https://github.com/user-attachments/assets/f5042a4d-29e1-4435-ac01-6b4f42b778cf


但在我的个人电脑和虚拟机均未出现此问题，如果仍无法解决此问题或许会考虑阉割动画效果

**Comment by alexliu07** [comment]
我这边班级电脑 我自己的电脑 虚拟机里都能复现
怀疑是动画与上课提醒的动画冲突，导致浮窗动画未启动，窗口卡在动画起始位置

**Comment by leohu1** [comment]
bug可以复现，再第一次切换到浮窗时
报错如下
```
UpdateLayeredWindowIndirect failed for ptDst=(1230, -50), size=(100x71), dirty=(140x97 -20, -14) (参数错误。)
```

**Comment by RinLit-233-shiroko** [comment]
对了，是只有开启“上课时自动隐藏”会出现这个问题吗还是

**Comment by alexliu07** [comment]
> 对了，是只有开启“上课时自动隐藏”会出现这个问题吗还是

对的，“最大化时隐藏”没有这个问题
