### ISSUE TITLE
日期不会定时更新

### ISSUE THREAD

**Issue by leohu1** [Class-Widgets/Class-Widgets#157]
### 检查清单

- [X] 我已更新到最新版 ![GitHub Release](https://img.shields.io/github/v/release/RinLit-233-shiroko/Class-Widgets?include_prereleases) ，并看过[最新提交](https://github.com/RinLit-233-shiroko/Class-Widgets/commits/main/)，确认这一 Bug 还没有修复。
- [X] 我已在 [Issues](https://github.com/RinLit-233-shiroko/Class-Widgets/issues?q=label%3ABug) 中检索，确认这一 Bug 未被提交过。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题（关于其他非程序本身的问题应当在 Discussion 板块提出）。

### 期望的行为

日期隔一段时间会自动更新

### 实际结果

不重启软件日期不会更新

### 重现步骤

一晚上不关电脑

### 应用版本

所有

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题。如果我的 issue 没有按照上述的要求填写，可能会被无条件关闭。

**Comment by wuyufeng9960** [comment]
也许根本就没有想到会有人一晚上不关电脑（好像这种情况课表也不会更新）


发自我的 Apple Watch

**Comment by RinLit-233-shiroko** [comment]
好

**Comment by Yersmagit** [comment]
课表好像会更新的 但日期不会
