### ISSUE TITLE
请求提供 32 位程序构建

### ISSUE THREAD

**Issue by UlinoyaPed** [Class-Widgets/Class-Widgets#158]
### 检查清单

- [X] 我已更新到最新版 ![最新的版本号](https://img.shields.io/github/v/release/RinLit-233-shiroko/Class-Widgets?include_releases&style=flat-square&label=) ，并看过[最新提交](https://github.com/RinLit-233-shiroko/Class-Widgets/commits/main/)，确认我想要的功能还没有实现。
- [X] 我已在 [Issues](https://github.com/RinLit-233-shiroko/Class-Widgets/issues?q=label%3ABug) 中检索，确认这一 Bug 未被提交过。
- [X] 我认为我想要的功能是用户广泛需要的，插件不能替代的，且没有超出 **软件本来** 的开发目标，而非 **添加与课表及教学辅助无关的内容** 。
- [X] 我已知晓由于开发者时间精力有限，我提交的功能请求可能需要比较久的时间才能实现。

### 背景与动机

学校的希沃白板是 win7 32 位的
> 学校不知道从哪儿搞的，太垃圾了，我自己写的东西也得专门编译一个 32 位的

但是 GitHub action 的 build 只有 amd64 架构

### 想要实现或优化的功能

在构建时打包一个 32位的 python 解释器

另：如果这事儿实在干不了，电脑上装 python 环境是否可以直接双击 main.py 从源码运行

### 最后一步

- [X] 我认为上述的描述已经足以详细，以便开发人员理解您想要的功能。如果我的 issue 没有按照上述的要求填写，可能会被无条件关闭。

**Comment by MKStoler4096** [comment]
@UlinoyaPed  可以，我试过python3.10 32-bit（装的时候加入path）：
首先，先`pip install -r requirements.txt`再`python main.py`

**Comment by UlinoyaPed** [comment]
> @UlinoyaPed 可以，我试过python3.10 32-bit（装的时候加入path）： 首先，先`pip install -r requirements.txt`再`python main.py`

https://github.com/Class-Widgets/Class-Widgets/issues/44#issuecomment-2382292012 里提到py 3.10不支持win7，请问后续都将以py 3.8.10为标准开发吗

我明天去学校电脑装py 3.8.10试一下

**Comment by MKStoler4096** [comment]
3.8不好说，看着应该可以

**Comment by xuanxuan1231** [comment]
pyqt6也要去除对python3.8的支持了https://www.riverbankcomputing.com/static/Docs/PyQt6/eol_policy.html

**Comment by RinLit-233-shiroko** [comment]
> python39起就去除了对win7的支持，然而pyqt6也要去除对python3.8的支持了https://www.riverbankcomputing.com/static/Docs/PyQt6/eol_policy.html

在之后会转向PyQt5的

**Comment by UlinoyaPed** [comment]
> 3.8不好说，看着应该可以
> 
> 有了 见 #159 

我今天尝试了 #79 构建

在win7 32位系统下双击主程序，显示报错提示框

```
Traceback (most recent call last):
  File "main.py", line 5, in <module>
ModuleNotFoundError: No module named 'pygetwindow'
```

所以目前是完全不支持 win7 吗，有没有至少能运行的办法

**Comment by xuanxuan1231** [comment]
我要revert了  pyqt6在32位环境上装不上

**Comment by xuanxuan1231** [comment]
自 https://github.com/Class-Widgets/Class-Widgets/commit/dce2758e311bed91367dcb571e0984ab279e6b57 起已经可以使用
Action: https://github.com/Class-Widgets/Class-Widgets/actions/runs/12162688448
