### ISSUE TITLE
悬浮窗的DPI似乎有问题

### ISSUE THREAD

**Issue by SparkleUesegi** [Class-Widgets/Class-Widgets#165]
### 检查清单

- [X] 我已更新到最新版 ![GitHub Release](https://img.shields.io/github/v/release/RinLit-233-shiroko/Class-Widgets?include_prereleases) ，并看过[最新提交](https://github.com/RinLit-233-shiroko/Class-Widgets/commits/main/)，确认这一 Bug 还没有修复。
- [X] 我已在 [Issues](https://github.com/RinLit-233-shiroko/Class-Widgets/issues?q=label%3ABug) 中检索，确认这一 Bug 未被提交过。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题（关于其他非程序本身的问题应当在 Discussion 板块提出）。

### 期望的行为

![image](https://github.com/user-attachments/assets/cecacef5-6144-4726-ba49-60b2c816ffcd)

### 实际结果

![image](https://github.com/user-attachments/assets/bf664901-e223-40e5-8909-d41cd3edaf22)

### 重现步骤

安装新的构建

### 应用版本

1.1.7_b4 构建 #90: Commit af96ef6 pushed by RinLit-233-shiroko

### 操作系统版本

11.0.22631.4317

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题。如果我的 issue 没有按照上述的要求填写，可能会被无条件关闭。

**Comment by xuanxuan1231** [comment]
当前最新构建可以100%复现

**Comment by RinLit-233-shiroko** [comment]
收到。这是由于软件框架切换至PyQt5导致的Bug，在PyQt5若要适配高分屏需要手动开启。会修复了

**Comment by RinLit-233-shiroko** [comment]
最新commit 774b713 已修复
