### ISSUE TITLE
课表到达最后三节课会显示为暂无课程

### ISSUE THREAD

**Issue by Detritalw** [Class-Widgets/Class-Widgets#167]
### 检查清单

- [X] 我已更新到最新版 ![GitHub Release](https://img.shields.io/github/v/release/RinLit-233-shiroko/Class-Widgets?include_prereleases) ，并看过[最新提交](https://github.com/RinLit-233-shiroko/Class-Widgets/commits/main/)，确认这一 Bug 还没有修复。
- [X] 我已在 [Issues](https://github.com/RinLit-233-shiroko/Class-Widgets/issues?q=label%3ABug) 中检索，确认这一 Bug 未被提交过。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题（关于其他非程序本身的问题应当在 Discussion 板块提出）。

### 期望的行为

正常显示课程

### 实际结果

[冬令时.json](https://github.com/user-attachments/files/18050194/default.json)
以上为课程表
由于只能显示单时间段，所以我将所有课程添加为在一个时间段内，但每天到达最后三节课的自习前半个小时，程序显示`暂无课程，无，无，无`，并且到时间也不会自动隐藏和上课提示。

### 重现步骤

1.使用这个课表
2.到达17:30时，课表显示 `暂无课程，无，无，无`

### 应用版本

1.1.7 Beta 3

### 操作系统版本

Windows 11与Windows 10

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题。如果我的 issue 没有按照上述的要求填写，可能会被无条件关闭。

**Comment by MKStoler4096** [comment]
用最新 actions 构建测试一下，疑似这是个旧 bug @Detritalw

**Comment by RinLit-233-shiroko** [comment]
确实，应该是旧Bug。在我这里测试是正常的

**Comment by RinLit-233-shiroko** [comment]
https://github.com/Class-Widgets/Class-Widgets/actions 可以在这里下载最新构建
