### ISSUE TITLE
移除“当前活动”小组件后 其它小组件自动更新功能失效

### ISSUE THREAD

**Issue by Yersmagit** [Class-Widgets/Class-Widgets#170]
### 检查清单

- [X] 我已更新到最新版 ![GitHub Release](https://img.shields.io/github/v/release/RinLit-233-shiroko/Class-Widgets?include_prereleases) ，并看过[最新提交](https://github.com/RinLit-233-shiroko/Class-Widgets/commits/main/)，确认这一 Bug 还没有修复。
- [X] 我已在 [Issues](https://github.com/RinLit-233-shiroko/Class-Widgets/issues?q=label%3ABug) 中检索，确认这一 Bug 未被提交过。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题（关于其他非程序本身的问题应当在 Discussion 板块提出）。

### 期望的行为

其它小组件自动更新功能正常运行

### 实际结果

在自定义页面中移除“当前活动”小组件后，其它小组件（包括活动倒计时、插件）自动更新功能失效

### 重现步骤

1. 打开软件
2. 在自定义设置页面移除“当前活动”组件
3. 重启软件
4. 问题出现，小组件无法自动更新内容（如图
   ![QQ_1733640492662](https://github.com/user-attachments/assets/c2e6b5d9-56a0-4eba-8342-25ce38032893)

### 应用版本

1.1.7-b4, 最新 commit 7e492676040495257bad84e3f0b462b3714e2e11

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题。如果我的 issue 没有按照上述的要求填写，可能会被无条件关闭。

**Comment by RinLit-233-shiroko** [comment]
修复了
