### ISSUE TITLE
节点为空时，添加课间并保存，重新打开设置界面初始化错误

### ISSUE THREAD

**Issue by pizeroLOL** [Class-Widgets/Class-Widgets#185]
### 检查清单

- [X] 我已更新到最新版 ![GitHub Release](https://img.shields.io/github/v/release/RinLit-233-shiroko/Class-Widgets?include_prereleases) ，并看过[最新提交](https://github.com/RinLit-233-shiroko/Class-Widgets/commits/main/)，确认这一 Bug 还没有修复。
- [X] 我已在 [Issues](https://github.com/RinLit-233-shiroko/Class-Widgets/issues?q=label%3ABug) 中检索，确认这一 Bug 未被提交过。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题（关于其他非程序本身的问题应当在 Discussion 板块提出）。

### 期望的行为

在时间线为空时阻止添加，或添加时验证时间线弹窗阻止添加

### 实际结果

![图片](https://github.com/user-attachments/assets/885748ee-c518-4d60-87f7-7a6364b50aab)

![图片](https://github.com/user-attachments/assets/fb931ee3-9bb3-476a-bd26-1a82049a80ce)

![图片](https://github.com/user-attachments/assets/91fad2f0-93f1-4028-90b0-ad3cdce41c79)

### 重现步骤

1. 在时间线为空时添加一个课间
2. 保存
3. 关闭设置
4. 重新打开设置

### 堆栈跟踪（可选）

```shell
2024-12-17 17:47:41.768 | ERROR    | menu:__init__:362 - 初始化设置界面时发生错误：'0'
```

### 应用版本

main 43601868150863b3cdd7db276ea4d6f42b21d4d6

### 操作系统版本

archlinux

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题。如果我的 issue 没有按照上述的要求填写，可能会被无条件关闭。

**Comment by xuanxuan1231** [comment]
配置文件的问题，应该和#184是一个问题

**Comment by RinLit-233-shiroko** [comment]
确实与 #184 重复
