### ISSUE TITLE
[BUG] 上课时自动隐藏模式下浮窗有概率无法正常完全显示

### ISSUE THREAD

**Issue by laoshuikaixue** [Class-Widgets/Class-Widgets#188]
### 检查清单

- [X] 我已更新到最新版 ![GitHub Release](https://img.shields.io/github/v/release/RinLit-233-shiroko/Class-Widgets?include_prereleases) ，并看过[最新提交](https://github.com/RinLit-233-shiroko/Class-Widgets/commits/main/)，确认这一 Bug 还没有修复。
- [ ] 我已在 [Issues](https://github.com/RinLit-233-shiroko/Class-Widgets/issues?q=label%3ABug) 中检索，确认这一 Bug 未被提交过。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题（关于其他非程序本身的问题应当在 Discussion 板块提出）。

### 期望的行为

上课时自动隐藏功能下 浮窗可正常显示

### 实际结果

通常表现为展示不全/直接贴顶 并且只要有一次没有正常展示 接下来均无法正确展示 第一次正常展示 接下来都是正常的

### 重现步骤

概率复现 在实际课堂环境中出现的问题 且日志无报错 与#156 表现类似 但没有开启上课提醒

### 应用版本

Lastest（Github Actions）

### 操作系统版本

Windows 10

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题。如果我的 issue 没有按照上述的要求填写，可能会被无条件关闭。

**Comment by RinLit-233-shiroko** [comment]
收到
