### ISSUE TITLE
[Feature Request] 滚动页面触屏优化

### ISSUE THREAD

**Issue by laoshuikaixue** [Class-Widgets/Class-Widgets#190]
### 检查清单

- [X] 我已更新到最新版 ![最新的版本号](https://img.shields.io/github/v/release/RinLit-233-shiroko/Class-Widgets?include_releases&style=flat-square&label=) ，并看过[最新提交](https://github.com/RinLit-233-shiroko/Class-Widgets/commits/main/)，确认我想要的功能还没有实现。
- [X] 我已在 [Issues](https://github.com/RinLit-233-shiroko/Class-Widgets/issues?q=label%3ABug) 中检索，确认这一 Bug 未被提交过。
- [X] 我认为我想要的功能是用户广泛需要的，插件不能替代的，且没有超出 **软件本来** 的开发目标，而非 **添加与课表及教学辅助无关的内容** 。
- [X] 我已知晓由于开发者时间精力有限，我提交的功能请求可能需要比较久的时间才能实现。

### 背景与动机

滚动页面的触屏优化

### 想要实现或优化的功能

![image](https://github.com/user-attachments/assets/b1221cd7-80f6-4c44-8038-54a8e3038bab)
![image](https://github.com/user-attachments/assets/f983814b-9bd6-43ef-9369-59a6b95bf5bd)
![image](https://github.com/user-attachments/assets/27d1723b-5413-4351-97ec-d57dc7ddaf53)

在这些不需要排序的滚动页面 直接在上面直接滑动更为方便 不然触屏电脑得拉旁边的条 麻烦

### 最后一步

- [X] 我认为上述的描述已经足以详细，以便开发人员理解您想要的功能。如果我的 issue 没有按照上述的要求填写，可能会被无条件关闭。

**Comment by xuanxuan1231** [comment]
与 #85 重复

**Comment by laoshuikaixue** [comment]
重复关闭
