### ISSUE TITLE
UOS 无法打开软件

### ISSUE THREAD

**Issue by MKStoler4096** [Class-Widgets/Class-Widgets#192]
### 检查清单

- [X] 我已更新到最新版 ![GitHub Release](https://img.shields.io/github/v/release/RinLit-233-shiroko/Class-Widgets?include_prereleases) ，并看过[最新提交](https://github.com/RinLit-233-shiroko/Class-Widgets/commits/main/)，确认这一 Bug 还没有修复。
- [X] 我已在 [Issues](https://github.com/RinLit-233-shiroko/Class-Widgets/issues?q=label%3ABug) 中检索，确认这一 Bug 未被提交过。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题（关于其他非程序本身的问题应当在 Discussion 板块提出）。

### 期望的行为

打开呗

### 实际结果

寄了

### 重现步骤

在 统信UOS家庭版 下运行。

### 堆栈跟踪（可选）

```shell
root@2023UOS:/home/others/Downloads/Linux-x64# ./ClassWidgets
[PYI-10972:ERROR] Failed to load Python shared library '/home/others/Downloads/Linux-x64/libpython3.8.so.1.0': dlopen: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /home/others/Downloads/Linux-x64/libpython3.8.so.1.0)
```

### 应用版本

最新Actions构建

### 操作系统版本

5.10.0-amd64-desktop（家庭版（22.0））

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题。如果我的 issue 没有按照上述的要求填写，可能会被无条件关闭。

**Comment by pizeroLOL** [comment]
1. 正常现象，pyinstaller 依赖的 glibc 和打包机器上一样
2. 建议源代码克隆到本机上创建虚拟环境运行，如果想要打包二进制文件请在自己机器上根据 workflow 上的步骤自行打包

**Comment by MKStoler4096** [comment]
行吧，我根本不会用 Linux。昨天研究了一个晚上 Python 3.10 怎么装上，也没有成功（）

原生 Python 3.7 ，在装 Requirements 的时候找不到合适版本。

**Comment by xuanxuan1231** [comment]
如果要构建后就能用的话，可能需要自己部署runner了

**Comment by MKStoler4096** [comment]
> 如果要构建后就能用的话，可能需要自己部署runner了

那样就又麻烦各位了……看看能不能出个简单的教程……

**Comment by xuanxuan1231** [comment]
> 如果要构建后就能用的话，可能需要自己部署runner了

我现在正在我自己的fork里测试，但是服务器性能很垃圾

**Comment by pizeroLOL** [comment]
https://devguide.python.org/versions/

emm，3.7 2023 年 eol，3.8 在 2024 eol，感觉未来的向下适配会越来越难做

**Comment by pizeroLOL** [comment]
> 那样就又麻烦各位了……看看能不能出个简单的教程……

能帮我测试一下吗？

```bash
# 安装 uv https://docs.astral.sh/uv/getting-started/installation/
curl -LsSf https://astral.sh/uv/install.sh | sh

# 安装 python https://docs.astral.sh/uv/guides/install-python/#next-steps
uv python install 3.8 # 选 3.8 是因为之前 win 7 支持是 3.8

# 建立虚拟环境 https://docs.astral.sh/uv/pip/environments/#creating-a-virtual-environment
uv venv -p 3.8

# 进入虚拟环境
source .venv/bin/activate

# 安装依赖
uv pip install -r requirements.linux.txt

# 运行
python main.py

# 安装打包工具
uv pip install pyinstaller

# 打包 https://github.com/Class-Widgets/Class-Widgets/blob/main/.github/workflows/build.yml
pyinstaller main.py \
    -w \
    -i ./img/favicon.ico \
    -n ClassWidgets \
    --contents-directory . \
    --add-data config:config \
    --add-data audio:audio \
    --add-data img:img \
    --add-data ui:ui \
    --add-data font:font \
    --add-data "*.ui":. \
    --add-data LICENSE:. \
    --add-data plugins:plugins
```

**Comment by xuanxuan1231** [comment]
我倒觉得可以写一个一键脚本之类的

**Comment by xuanxuan1231** [comment]
@MKStoler4096 https://github.com/xuanxuan1231/Class-Widgets/actions/runs/12454958258 好了，试试吧
用 debian 10 构建的，这回应该是可以了

**Comment by MKStoler4096** [comment]
在班电脑上 ArchLinux 虚拟机下运行毛事没有，还是要等回家或者那边级部的老哥找我……

**Comment by MKStoler4096** [comment]
好了，我 ArchLinux 也打不开了
Ubuntu 构建的：
![image](https://github.com/user-attachments/assets/7b7d1c69-8525-4af8-b9c4-9e04b195d595)
Debian 构建的：
![image](https://github.com/user-attachments/assets/f5bf8d5a-dda2-433a-a1ee-fc66e99da956)

**Comment by xuanxuan1231** [comment]
也可能是缺运行库（？

**Comment by pizeroLOL** [comment]
https://packages.debian.org/bullseye/amd64/libcrypt1/filelist

**Comment by pizeroLOL** [comment]
@MKStoler4096 能在桌面的cw2目录下ls -la一下吗，我怀疑你没法执行ubuntu编译的class widgets是因为你用sudo启动过

**Comment by MKStoler4096** [comment]
> @MKStoler4096 能在桌面的cw2目录下ls -la一下吗，我怀疑你没法执行ubuntu编译的class widgets是因为你用sudo启动过

过

行（我看看

**Comment by xuanxuan1231** [comment]
跑起来了 见 #207
需要手动装一个 libxcb-util1

**Comment by MKStoler4096** [comment]
OK
