### ISSUE TITLE
[BUG] 触屏状态下拖动时渲染层出错

### ISSUE THREAD

**Issue by liubanlaobanzhang** [Class-Widgets/Class-Widgets#196]
### 检查清单

- [X] 我已更新到最新版 ![GitHub Release](https://img.shields.io/github/v/release/RinLit-233-shiroko/Class-Widgets?include_prereleases) ，并看过[最新提交](https://github.com/RinLit-233-shiroko/Class-Widgets/commits/main/)，确认这一 Bug 还没有修复。
- [X] 我已在 [Issues](https://github.com/RinLit-233-shiroko/Class-Widgets/issues?q=label%3ABug) 中检索，确认这一 Bug 未被提交过。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题（关于其他非程序本身的问题应当在 Discussion 板块提出）。

### 期望的行为

正常拖动

### 实际结果

上图：
![image](https://github.com/user-attachments/assets/b3162623-1413-48b0-9465-28ae8941e252)

### 重现步骤

直接打开 Class Widgets 设置界面，在课程表内鼠标左键拖动/使用触屏拖动

### 应用版本

1.1.7-b4（ff8f09b）

### 操作系统版本

24H2,26100.2605

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题。如果我的 issue 没有按照上述的要求填写，可能会被无条件关闭。

**Comment by RinLit-233-shiroko** [comment]
这个不是很重要吧，而且算是组件库的Bug。故在短期不会考虑修复
