### ISSUE TITLE
将时间线拖动到其他时间线之间，时间线并没有反应。

### ISSUE THREAD

**Issue by CXDark** [Class-Widgets/Class-Widgets#67]
### 检查清单

- [X] 我已更新到最新版 ![GitHub Release](https://img.shields.io/github/v/release/RinLit-233-shiroko/Class-Widgets?include_prereleases) ，并看过[最新提交](https://github.com/RinLit-233-shiroko/Class-Widgets/commits/main/)，确认这一 Bug 还没有修复。
- [X] 我已在 [Issues](https://github.com/RinLit-233-shiroko/Class-Widgets/issues?q=label%3ABug) 中检索，确认这一 Bug 未被提交过。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题（关于其他非程序本身的问题应当在 Discussion 板块提出）。

### 期望的行为

修复此bug

### 实际结果

时间线并未变动

### 重现步骤

第一步：先新创建一条时间线
![QQ20240923-224849](https://github.com/user-attachments/assets/c226ec3b-ac77-4268-a62c-58b014d8d1cc)
第二步：将新时间线移到其他时间线之间
![QQ20240923-224915](https://github.com/user-attachments/assets/c24424a0-62c6-4fad-a79d-e65f0d76854a)
结果：新时间线并没有变到其他时间线之间，新时间线在其他时间线后面
![QQ20240923-224955](https://github.com/user-attachments/assets/69715108-be3a-4e87-b459-0841cdff97d9)

### 应用版本

v1.1.6.5最新版

### 操作系统版本

Windows 10 22H2

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题。如果我的 issue 没有按照上述的要求填写，可能会被无条件关闭。

### 不要乱下载别人发的文件，特别是名字是fix.zip的文件。您是否遇见过这样的文件？

否

**Comment by CXDark** [comment]
希望作者可以抽出时间快速处理此问题，此问题已经影响到使用。 @RinLit-233-shiroko @MKStoler4096

**Comment by CXDark** [comment]
bug视频重现
https://github.com/user-attachments/assets/4bc4eeed-3971-4626-891d-4bbd91f52994

**Comment by CXDark** [comment]
严重bug重现

https://github.com/user-attachments/assets/6682e5b6-92f1-4a68-b5d6-3501cfdddf71


@RinLit-233-shiroko

**Comment by MKStoler4096** [comment]
莫要at我啊，我只负责帮忙看看bug提提意见🤣
@CXDark 盲猜程序的listbox并没有绑定拖拽方法……拽过去了还是原来的位置……
时间上也会是上午课程的延续……

**Comment by CXDark** [comment]
@MKStoler4096 希望可以帮忙通知一下 @RinLit-233-shiroko 修复一下

**Comment by MKStoler4096** [comment]
@CXDark 这算是个新功能了……可以close这个重发一个功能请求

**Comment by CXDark** [comment]
> @CXDark 这算是个新功能了……可以close这个重发一个功能请求

好的

**Comment by RinLit-233-shiroko** [comment]
这其实相当于要再写一堆功能了，有点复杂，短期内不会考虑
